### ISSUE TITLE
[BUG, AND BUG FIX]

### ISSUE THREAD

**Issue by deBBuu** [DmACKGL/GCPhone-Rewrite#66]
I found a solution to fix bugs:
- phone animation when u get message 
- calling people

I don't know why but you need to delete ` if hasPhone() then`  in line 331

and replace event in line 441
<pre>
RegisterNetEvent("gcPhone:waitingCall")
AddEventHandler("gcPhone:waitingCall", function(infoCall, initiator)
  SendNUIMessage({event = 'waitingCall', infoCall = infoCall, initiator = initiator})
  if initiator == true then
    PhonePlayCall()
    if menuIsOpen == false then
      TooglePhone()
    end
  end
end)
</pre>
Also i found a new bug, when u have phone open and u receive a message - animation will trigger... dont know how to fix it

**Comment by HezimX** [comment]
Are you using the reales version?

**Comment by deBBuu** [comment]
i fixed triggering anim when phone open 

replace from line 326 to 360

<pre>
RegisterNetEvent("gcPhone:receiveMessage")
AddEventHandler("gcPhone:receiveMessage", function(message)
  -- SendNUIMessage({event = 'updateMessages', messages = messages})
  SendNUIMessage({event = 'newMessage', message = message})
  table.insert(messages, message)
    if menuIsOpen == false and message.owner == 0 then
      local app = _U('new_message')
      if Config.ShowNumberNotification == true then
        app = _U('new_message_from', message.transmitter)
        for _,contact in pairs(contacts) do
          if contact.number == message.transmitter then
            app = _U('new_message_transmitter', contact.display)
            break
          end
        end
      end

      SendNUIMessage({event = 'updateNotification', active = true})
      SendNUIMessage({
        event = 'updateNotificationInfo', 
        info = {
          app = app,
          icon = 'sms',
          prefix = 'fas',
          color = '#87fc6a',
          message = message
        }
      })
      PlaySound(-1, "Menu_Accept", "Phone_SoundSet_Default", 0, 0, 1)
      Citizen.Wait(300)
      PlaySound(-1, "Menu_Accept", "Phone_SoundSet_Default", 0, 0, 1)
      Citizen.Wait(300)
      PlaySound(-1, "Menu_Accept", "Phone_SoundSet_Default", 0, 0, 1)
    end
end)
</pre>

**Comment by deBBuu** [comment]
> 
> 
> Are you using the reales version?

im using newest version of phone and esx_addons_gcphone

**Comment by HezimX** [comment]
Dont need to remove hasPhone allready fixed in this commit
You need to download from the git not the newst version
Esx_addons_gcphone think you dont need it it in gcphone/addons

https://github.com/DmACKGL/GCPhone-Rewritten/commit/7e554d288afdd42ad013f2bda98e170cb9d2e564

**Comment by HezimX** [comment]
> Dont need to remove hasPhone allready fixed in this commit
> You need to download from the git not the newst version
> and i think you dont need esx_addons_gcphone its in addons in this phone

> [7e554d2](https://github.com/DmACKGL/GCPhone-Rewritten/commit/7e554d288afdd42ad013f2bda98e170cb9d2e564)

**Comment by deBBuu** [comment]
> 
> 
> Dont need to remove hasPhone allready fixed in this commit
> You need to download from the git not the newst version
> 
> [7e554d2](https://github.com/DmACKGL/GCPhone-Rewritten/commit/7e554d288afdd42ad013f2bda98e170cb9d2e564)

Yea you're right i had older version... now everything works perfectly but still i recommend changing 333 line to this 
` if menuIsOpen == false and message.owner == 0 then` 

Im using esx_addons_gcphone for police/ambulance dispatch
